# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRN', models.CharField(max_length=6)),
                ('Subj', models.CharField(max_length=4)),
                ('Crse', models.CharField(max_length=6)),
                ('Sec', models.CharField(max_length=6)),
                ('Cred', models.FloatField()),
                ('Title', models.CharField(max_length=50)),
                ('Days', models.CharField(max_length=7)),
                ('Time_begin', models.TimeField()),
                ('Time_end', models.TimeField()),
                ('Instructor', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=15)),
                ('Attribute', models.CharField(max_length=30)),
            ],
        ),
    ]
